name: Build Avalonia App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # .exeビルドのため、Windowsランナーを使用します

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'  # 使用している.NETバージョンに合わせてください

    - name: Restore dependencies
      run: dotnet restore Starter.sln

    - name: Build the project
      run: dotnet build Starter.sln --configuration Release

    - name: Publish for Windows (.exe)
      run: dotnet publish Starter.sln -c Release -r win-x64 --self-contained false --output ./publish/windows

    - name: Publish for macOS (.app)
      run: dotnet publish Starter.sln -c Release -r osx-x64 --self-contained false --output ./publish/osx

    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: ./publish/windows

    - name: Upload macOS build artifact
      uses: actions/upload-artifact@v3
      with:
        name: osx-build
        path: ./publish/osx
